### PR TITLE
Plone 6 compatibiity

### PR DESCRIPTION
**Pull request by thet**

### CODE REVIEW

**Review by ale-rt — CHANGES_REQUESTED** [review]
Generally speaking, when you remove `<includeDependencies package="." />` you have to explicitely list the packages you need to include:
```
<include package="foo" />
<include package="bar" />
...
```

**Comment by thet** [comment]
@ale-rt I ask myself if the `configure.zcml` is needed at all. Do you also think we can remove it from this package?

**Comment by ale-rt** [comment]
In the `install_requires` it says Plone. 
I am not sure if removing the `configure.zcml` will be a cause of problems.
If some project adds it to the zcml it will cause troubles.
Removing it might be a bold move.

**Comment by thet** [comment]
@ale-rt there is no configure.zcml in the Plone package: https://github.com/plone/Plone . 
But Plone depends on other packages. I think `includeDependencies` does not recursively include zcml but only what's directly defined in setup.py, no?

**Comment by thet** [comment]
Reading the readme of https://github.com/zopefoundation/z3c.autoinclude I'm pretty sure that `includeDependencies` is only including direct dependencies of the current package. So, I think we do not need to include any extra dependencies zlc.zopescript's configure.zcml

**Review by ale-rt — APPROVED** [review]
Let's see how it works, I will release an alpha version here

**Pull request merged**
